dist: trusty
sudo: false 
language: C
compiler: gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "uoqtYvZyc3cjw0FaQtxKKeVvjY1aVyz6T/nQb234ASeW4NFBOw/Sx0muszlEIBRXCTAcbj4GhmNeG5ZGeZAK2dcVliktVR7W97BPFBBqODB/eUUj0O8FvPKOZU2NEWzr+45EDLpO24KW3Q25rZQb4dFhiMrzUdrWw7XlSWxcsLT6JbhtKiOw558Sdyxnv7bInappedOVWNT7IBiUi4fLyb1n2zaL6QWO5xWCPGDb3y7K4VvdYRep3N5o+v9lFzdqQanl/TnuL7gbtLnZC+ch9hwdHMQNdTMNivxVKeSsDly0f8OhYB6HqL+61QlBd61MSGP/RFlpSAaJ5fFe+sl1Lk/tuJOVPmTYKVcQXbhgrhZ28oQcaiam0t7EwqLJeaySRnbi3WWp9PLiPfxvVkq69VS5GN3uhZmnYzIWw4JzReTeysoLKkc+/AxGJkWd0YhYBJUggQHyNUzH2aaKSs0SIKzKCKf3KSJXBPca1ZlGha9TbbHXc8jkPL3nKxm/xGbRlojBatF2cAvLR8hRiSR17OHmzUT4L7dxVxIf++M4x4WJsyuPpc3Re9fwbxnQKjbOOTaSN30yOewlNKoLT7AxyOZ940huh6zE9ugk/xnmaM3YkUpY98pC6giIK772L6Buz8uSFNHSV4kycWq2qEaIPA/kw3eMIOuVTNWDoye/GKo="

addons:
  apt: 
    packages:
      - libmicrohttpd-dev
      - libjansson-dev
      - libnice-dev
      - libssl-dev
      - libsofia-sip-ua-dev
      - libglib2.0-dev
      - libcurl4-openssl-dev
      - gengetopt
      - libconfig-dev
  coverity_scan:
    project:
      name: "dazzl-tv/janus-gateway"
      description: "Build submitted via Travis CI"
    notification_email: manux@rioungo.fr
    build_command_prepend: "./travis.sh janus_configure"
    build_command:   "./travis.sh janus_build"
    branch_pattern: coverity_scan

before_script:
 - cd ..
# create install directories
 - mkdir -p install/srtp install/boringssl install/usrsctp install/rabbit
# install libsrtp
 - wget https://github.com/cisco/libsrtp/archive/v2.0.0.tar.gz
 - tar xfv v2.0.0.tar.gz
 - cd libsrtp-2.0.0
 - ./configure --prefix=${HOME}/install/srtp --enable-openssl
 - make shared_library && make install
# install boringssl
 - cd ..
 - git clone https://boringssl.googlesource.com/boringssl
 - cd boringssl
 - sed -i s/" -Werror"//g CMakeLists.txt
 - mkdir -p build
 - cd build
 - cmake -DCMAKE_CXX_FLAGS="-lrt" ..
 - make
 - cd ..
 - rsync -av include ${HOME}/install/boringssl
 - mkdir -p ${HOME}/install/boringssl/lib
 - cp build/ssl/libssl.a build/crypto/libcrypto.a ${HOME}/install/boringssl/lib
# install usrsctp
 - cd ..
 - git clone https://github.com/sctplab/usrsctp
 - cd usrsctp
 - ./bootstrap
 - ./configure --prefix=${HOME}/install/usrsctp
 - make && make install
# install rabbitmq
 - cd ..
 - git clone https://github.com/alanxz/rabbitmq-c
 - cd rabbitmq-c
 - git submodule init
 - git submodule update
 - mkdir build && cd build
 - cmake -DCMAKE_INSTALL_PREFIX=${HOME}/install/rabbit ..
 - make && make install && cd ..
# back to janus 
 - cd ../janus-gateway

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./travis.sh janus_all ; fi

